name: Test workflow

on:
  push:
    
jobs:
  echo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the name
        run: |
          echo "Hello ${{ github.event_name }}"
          export NAME=Mathias
          echo the $NAME